name: surgery_memo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  path_provider: ^2.0.0
  record: ^5.0.0
  file_picker: ^6.1.0
  audioplayers: ^6.6.0
  speech_to_text: ^5.5.0
  firebase_core: ^4.6.0
  firebase_auth: ^6.3.0
  firebase_ai: ^3.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
