// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1K182tYI39fwohPhs3hAmRv8yzkMQky0',
    appId: '1:514630778460:android:52997cdd384d4bfc84b099',
    messagingSenderId: '514630778460',
    projectId: 'surgery-counselling-memo',
    storageBucket: 'surgery-counselling-memo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfHRPORh1N1ObdRfHQEYI2Eov0qiT6wik',
    appId: '1:514630778460:ios:5109c3b28383da0084b099',
    messagingSenderId: '514630778460',
    projectId: 'surgery-counselling-memo',
    storageBucket: 'surgery-counselling-memo.firebasestorage.app',
    iosBundleId: 'com.noda.sklog',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC59TKk8jdwTjZONbmUiS4EIRcmKfLVNxA',
    appId: '1:514630778460:web:6ceb05d78e9684c984b099',
    messagingSenderId: '514630778460',
    projectId: 'surgery-counselling-memo',
    authDomain: 'surgery-counselling-memo.firebaseapp.com',
    storageBucket: 'surgery-counselling-memo.firebasestorage.app',
  );

}